addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 5d73753a-4806-47c0-b615-7411e7eb40b8
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- nvm install 0.10
- node --version
- npm install -g bower
- npm install -g grunt && npm install -g grunt-cli
- grunt --version
- ruby -v
- gem install sass
- sass -v
- gem install compass
- compass version
branches: ''
cache:
  directories:
  - $HOME/.m2
env:
- MAVEN_OPTS=-Xmx1024M
install: echo 'Skipping install stage, dependencies will be downloaded during build
  and test stages.'
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=5d73753a-4806-47c0-b615-7411e7eb40b8
script:
- mvn clean install license:check -Dmaven.test.skip=false -DskipITs=false -P !assembly
  -B -V -Dsurefire.rerunFailingTestsCount=2
- cd dspace && mvn package -Dmirage2.on=true -Dmirage2.deps.included=false -P !assembly
  -B -V -Dsurefire.rerunFailingTestsCount=2
sudo: false
# Modified by Insights Service at 2016-11-22 11:43:52.204924
